name: Fame the Name
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Name to add"
        required: true
      directory:
        description: "Directory of the Wall of Fame file"
        required: true

env:
  TARGET_FILE: "Wall_of_Fame.md"
  TARGET_DIR: ${{ github.event.inputs.directory }}

jobs:
    hello:
        runs-on: ubuntu-latest

        steps:
        - name: Hello Step
          run: echo "Hello ${{ github.event.inputs.name }}"
